FROM python:3.7-slim

RUN apt-get update && apt-get install -y \
    binutils \
    libproj-dev \
    gdal-bin \
    curl \
    && rm -rf /var/lib/apt/lists/*
ENV PYTHONUNBUFFERED=1
ADD requirements.txt .
RUN pip install -r requirements.txt

COPY . /app
WORKDIR /app
RUN mkdir -p ./media/admin
RUN mkdir -p ./media/sale_images

EXPOSE 8000
RUN chmod a+x ./django_run.sh
CMD ["./django_run.sh"]