# Generated by Django 2.2 on 2019-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_finder_app', '0002_auto_20190411_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsaleinfo',
            name='url_fingerprint',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='spiderrun',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
