# Generated by Django 2.2 on 2019-04-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_finder_app', '0003_auto_20190411_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsaleinfo',
            name='new_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
