# Generated by Django 3.1.3 on 2020-11-16 17:55

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_finder_app', '0004_carsaleinfo_new_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsaleinfo',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles', to='car_finder_app.city')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactured', models.IntegerField(blank=True, null=True)),
                ('purchased', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('horse_power', models.SmallIntegerField(blank=True, null=True)),
                ('engine_type', models.CharField(max_length=20)),
                ('gear_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('url_fingerprint', models.CharField(db_index=True, max_length=255, unique=True)),
                ('url', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cars', to='car_finder_app.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cars', to='car_finder_app.country')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cars', to='car_finder_app.generation')),
                ('last_spider_run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cars', to='car_finder_app.spiderrun')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cars', to='car_finder_app.carmodel')),
            ],
        ),
    ]
