# Generated by Django 3.1.3 on 2020-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_finder_app', '0005_auto_20201116_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsaleinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
