# Generated by Django 3.1.3 on 2020-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_finder_app', '0006_carsaleinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsaleinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sale_images/'),
        ),
    ]
